2024-07-11 21:31:32,375:INFO:Fetching range::::: 0-5242879 from http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,375:INFO:Fetching range::::: 5242880-10485759 from http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,375:INFO:Fetching range::::: 10485760-15728639 from http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,653:INFO:Delay 0.2779712677001953
2024-07-11 21:31:32,653:INFO:Successfully fetched range 0-5242879 from http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,653:INFO:Throughput: {'http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 18861226.353993837}
2024-07-11 21:31:32,653:INFO:number_of_chunk: 1
2024-07-11 21:31:32,653:INFO:Fetching range::::: 15728640-57671679 from http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,731:INFO:Delay 0.35587501525878906
2024-07-11 21:31:32,731:INFO:Successfully fetched range 10485760-15728639 from http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,731:INFO:Throughput: {'http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 18861226.353993837, 'http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 14732360.450163735}
2024-07-11 21:31:32,732:INFO:number_of_chunk: 2
2024-07-11 21:31:32,732:INFO:Fetching range::::: 57671680-68157439 from http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,832:INFO:Delay 0.45725464820861816
2024-07-11 21:31:32,833:INFO:Successfully fetched range 5242880-10485759 from http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,833:INFO:Throughput: {'http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 18861226.353993837, 'http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 14732360.450163735, 'http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 11465993.884457977}
2024-07-11 21:31:32,833:INFO:number_of_chunk: 3
2024-07-11 21:31:32,833:INFO:Fetching range::::: 68157440-78643199 from http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,881:INFO:Delay 0.14906859397888184
2024-07-11 21:31:32,882:INFO:Successfully fetched range 57671680-68157439 from http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:32,882:INFO:Throughput: {'http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 18861226.353993837, 'http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 70341838.7476405, 'http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 11465993.884457977}
2024-07-11 21:31:32,882:INFO:number_of_chunk: 4
2024-07-11 21:31:32,882:INFO:Fetching range::::: 78643200-120586239 from http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:33,055:INFO:Delay 0.40193772315979004
2024-07-11 21:31:33,055:INFO:Successfully fetched range 15728640-57671679 from http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:33,055:INFO:Throughput: {'http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 104352083.875754, 'http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 70341838.7476405, 'http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 11465993.884457977}
2024-07-11 21:31:33,055:INFO:number_of_chunk: 5
2024-07-11 21:31:33,056:INFO:Fetching range::::: 120586240-162529279 from http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:33,110:INFO:Delay 0.27703094482421875
2024-07-11 21:31:33,111:INFO:Successfully fetched range 68157440-78643199 from http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso
2024-07-11 21:31:33,111:INFO:Throughput: {'http://10.137.132.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 104352083.875754, 'http://10.134.48.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 70341838.7476405, 'http://10.135.163.2/Fedora-Everything-netinst-x86_64-38-1.6.iso': 37850497.195009775}
2024-07-11 21:31:33,111:INFO:number_of_chunk: 6
2024-07-11 21:42:40,802:ERROR:Task exception was never retrieved
future: <Task finished name='Task-1' coro=<main() done, defined at /home/ubuntu/assignmentAlgorithm/assignment.py:194> exception=KeyboardInterrupt()>
Traceback (most recent call last):
  File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
    msg = self.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
    return fmt.format(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
    record.message = record.getMessage()
  File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/assignmentAlgorithm/assignment.py", line 227, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 47, in run
    _cancel_all_tasks(loop)
  File "/usr/lib/python3.10/asyncio/runners.py", line 63, in _cancel_all_tasks
    loop.run_until_complete(tasks.gather(*to_cancel, return_exceptions=True))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/assignmentAlgorithm/assignment.py", line 207, in main
    await asyncio.gather(
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/ubuntu/assignmentAlgorithm/assignment.py", line 153, in download_file
    best_server_combinations = find_best_server_combination(remaining_size, throughput, 40*1024*1024, 10*1024*1024, urls)
  File "/home/ubuntu/assignmentAlgorithm/assignment.py", line 83, in find_best_server_combination
    logging.info("results",results)
  File "/usr/lib/python3.10/logging/__init__.py", line 2138, in info
    root.info(msg, *args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1477, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib/python3.10/logging/__init__.py", line 1624, in _log
    self.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1634, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1696, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 968, in handle
    self.emit(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1218, in emit
    StreamHandler.emit(self, record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1108, in emit
    self.handleError(record)
  File "/usr/lib/python3.10/logging/__init__.py", line 1038, in handleError
    sys.stderr.write('Message: %r\n'
KeyboardInterrupt
2024-07-11 21:42:40,802:ERROR:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe288038700>
2024-07-11 21:42:40,802:ERROR:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe2880396f0>
2024-07-11 21:42:40,802:ERROR:Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe2880390f0>
